### ISSUE TITLE
Multipart upload with ChecksumType.FULL_OBJECT not working

### ISSUE THREAD

**Issue by ackava** [adobe/S3Mock#2843]
As I have looked up the source code it seems ChecksumType.COMPOSITE is hardcoded in multi part upload so using ChecksumType.FULL_OBJECT fails on s3mock, but it does work correctly on aws s3.

[ChecksumType.COMPOSITE](https://github.com/adobe/S3Mock/blob/24d299bef06642ba60b478d27c6ae1f07e8a0ce8/server/src/main/kotlin/com/adobe/testing/s3mock/store/MultipartStore.kt#L221-L222)

```javascript

        // this fails with s3mock but works with aws s3
        await this.client.send(new CompleteMultipartUploadCommand({
            Bucket: this.Bucket,
            Key: this.Key,
            UploadId: uploadRequest.UploadId,
            ChecksumCRC64NVME: this.ChecksumCRC64NVME,
            ChecksumType: "FULL_OBJECT",
            MultipartUpload: {
                Parts
            }
        }));

```

instead of hardcoded `composite`, it should take `full_object` from the input parameter and support `full_object` checksum.

**Comment by afranken** [comment]
thanks for the report.
We indeed currently implement only "COMPOSITE" checksums for Multipart uploads.
"FULL_OBJECT" was added on later for Multipart uploads and S3Mock was never retrofitted.

I just pushed a fix that will be included in the first 5.x release and verified the new integration tests against S3 APIs.

**Comment by ackava** [comment]
@afranken Thank you for fixing this. This library is very useful for local testing.

**Comment by ackava** [comment]
This is still not working, checksum fails for FULL_OBJECT with ChecksumCRC64NVME.

**Comment by afranken** [comment]
did you build S3Mock locally from the branch I pushed the changes to?
I'm still waiting on CodeQL supporting Kotlin 2.3.0, see #2828 

The Fix for this issue will be released in 5.x
