### ISSUE TITLE
Tests failing on s3mock-junit5 v2.5.0

### ISSUE THREAD

**Issue by bpfoster** [adobe/S3Mock#782]
Hello and thanks for the great work!  I am testing upgrading to the new s3mock-junit5 2.5.0 from 2.4.16.  No other changes to the project except the dependency version change.

All existing unit tests that have `@SpringBootTest` now fail with the following:
```
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test

	at org.springframework.util.Assert.state(Assert.java:76)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:236)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:152)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:393)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildDefaultMergedContextConfiguration(AbstractTestContextBootstrapper.java:309)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:262)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:107)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:102)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:137)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:122)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$4(ExtensionValuesStore.java:86)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.computeValue(ExtensionValuesStore.java:223)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:211)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.evaluate(ExtensionValuesStore.java:191)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.access$100(ExtensionValuesStore.java:171)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:93)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:61)
	at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:294)
	at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:113)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by afranken** [comment]
@bpfoster thanks for the report. :)
We are testing the JUnit integrations ourselves in the project, but those are only smoke-tests without additional dependencies...

Is this a public repository where I could reproduce the error?

Weird, I did not remove configurations, only added more `@Configuration` classes...
I did update to Spring Boot 2.7.3, for example, which could always cause problems.
Looking at the `S3MockApplication`, we were using various annotations to configure S3Mock, but `@SpringBootConfiguration` was not one of them (and never was).
I have opened #785 which replaces those annotations with `@SpringBootApplication`, which includes `@SpringBootConfiguration`.

However, I can't tell if this actually fixes your problem, and how many other project will break with this change...

**Comment by afranken** [comment]
I am guessing that you are testing a Spring Boot application with this method?

Unfortunately, that will always be problematic - your application will add Spring libraries and configurations to the classpath, and this is mixed with the S3Mock.
Any dependency update or change to the S3Mock could break your tests at any time :(

My recommendation is to use the S3Mock Docker container, for example with [TestContainers](https://www.testcontainers.org/). This will isolate your application from the S3Mock, making your build more reliable against changes made to S3Mock in the future.

**Comment by afranken** [comment]
I just released 2.5.1 - could you try again? :)

**Comment by bpfoster** [comment]
Hi @afranken thanks for the quick response!

Looks like 2.5.1 did not fix it.
My real repo is not public but I think I've got it down to a pretty bare-bones reproduction:
https://github.com/bpfoster/s3mock-junit5-2.5-error

I am not familiar with TestContainers but will take your recommendation and look into if I can get it working for us!

**Comment by afranken** [comment]
@bpfoster thanks, I'll look into reproducing the error in your repo :)

**Comment by afranken** [comment]
thanks for the repo, found the problem:
It was introduced with #752 

Should have read the documentation carefully.
I understood that this is a non-breaking change where if S3Mock provides a [Component Index](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index), the application declaring the dependency would not be affected.

This is unfortunately not true - if _one_ library on the classpath includes a [Component Index](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index), the Spring Context decides to use the indexes only, completely ignoring all other (annotation based) configuration.

This is the error you're seeing: S3Mock is probably the only library providing a Component Index, so the rest of the application does not work because Spring ignores the annotations (like `@Configuration`, `@Component`, `@Service`, ...)

**Comment by afranken** [comment]
I will revert that change and make a new release, since it will break a high percentage of other integrations as well, at least if they are using Spring Boot for their application.

**Comment by afranken** [comment]
Potential workarounds would be:
Produce Spring Component Index files within your application, and cross your fingers that third party Spring libraries you're using are releasing versions of their software that include Component Indexes.

```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context-indexer</artifactId>
    <optional>true</optional>
</dependency>
```

or, disable Spring Component Index processing by setting

```
spring.index.ignore=true
```

**Comment by afranken** [comment]
Just released 2.5.3, so sorry for breaking your application.

However, I would still encourage you to look into TestContainers since it is very convenient not only for S3Mock, but databases and other services as well! 
I'll try to set up an example project using TestContainers in an integration test. :)

**Comment by bpfoster** [comment]
@afranken No worries - we were able to catch it prior to being integrated.

2.5.3 does indeed fix this for us - thank you for the very quick turnaround!
